version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
#  postgres:
#    image: postgres
#    environment:
#      - POSTGRES_POSSWORD=root
#      - POSTGRES_DB = fastapi
#    volumes:
#      - postgres-db: /var/lib/postgresql/data
#volumes:
#  postgres-db: