name: Build and Deploy Code

on: [push,pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling fit repos
        uses: actions/checkout@v2
      - name: say hi to amit
        run: echo "hello amit"
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirement.txt
#      - name: run the test
#        run: |
#          pip install pytest
#          pytest
      - name: Login To Docker Hub
        uses: docker/login-action@v1
        with:
          username: amit96pal
          password: 8ff9dbcb-ebd7-4a83-8137-12c378fbe055
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: amit96pal/fastapi:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}